spring:
  output.ansi.enabled: ALWAYS
  application:
    name: DareAndTruth
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dare_and_truth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PW:postgresql}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGODB_URL}
      database: ${MONGODB_DB:dodo}

logging:
  level:
    org:
      springframework.data.mongodb.core.MongoTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080

fe-server:
  url: ${FE_URL:http://localhost:3000}

openapi:
  service:
    api-docs: DareAndTruth-service
    title: Dare&Truth API Documentation
    version: ${API_DOC_VERSION:v0.0.1}
    server: ${BE_URL:http://localhost:8080}

app:
  timezone=Asia/Ho_Chi_Minh:
  jwt:
    secret: ${JWT_SECRET:5gZHYsLGeUB7TvtT9AbxlgaNXyUaykNzDgdK00yX5SPDXrNeCGBYNrngUym3ykRn}
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION:3600000}
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION:2592000000}